services:
  rag-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-test
    volumes:
      - .:/app
      - ./gdrive_service_account.json:/app/gdrive_service_account.json:ro
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: ["poetry", "run", "pytest", "--maxfail=3", "--disable-warnings", "-q"]

  rag-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-prod
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    entrypoint: ["poetry", "run", "python", "app/entrypoints/cli.py"]
    command: ["data/pdfs", "Welche Leuchte hat die Erzeugnisnummer 4062172212311?"]
